# Generated by Django 5.1.2 on 2024-11-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='eligibility_criteria',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='link',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='store_name',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='Unnamed Discount', max_length=100),
        ),
        migrations.AddField(
            model_name='discount',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
